export const AUDIT_ACTIONS = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',

  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_RESUBMITTED: 'PROJECT_RESUBMITTED',
  PROJECT_APPROVED: 'PROJECT_APPROVED',
  PROJECT_REJECTED: 'PROJECT_REJECTED',

  UPLOAD_TIMESHEET_SUCCESS: 'UPLOAD_TIMESHEET_SUCCESS',
  UPLOAD_TIMESHEET_REJECTED: 'UPLOAD_TIMESHEET_REJECTED',
  UPLOAD_BILLING_SUCCESS: 'UPLOAD_BILLING_SUCCESS',
  UPLOAD_SALARY_SUCCESS: 'UPLOAD_SALARY_SUCCESS',
  UPLOAD_SALARY_PARTIAL: 'UPLOAD_SALARY_PARTIAL',
  UPLOAD_SALARY_REJECTED: 'UPLOAD_SALARY_REJECTED',

  RECALCULATION_TRIGGERED: 'RECALCULATION_TRIGGERED',

  SHARE_LINK_CREATED: 'SHARE_LINK_CREATED',
  SHARE_LINK_REVOKED: 'SHARE_LINK_REVOKED',

  PDF_EXPORTED: 'PDF_EXPORTED',

  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
