import { describe, it, expect, beforeEach, afterAll } from 'vitest';
import { prisma } from '../lib/prisma.js';
import { cleanDb, seedTestDepartments, createTestUser, disconnectTestDb } from '../test-utils/db.js';

// Check if Puppeteer is available and functional
let puppeteerAvailable = false;
try {
  const puppeteer = await import('puppeteer');
  // Quick probe: can we launch a browser?
  const browser = await puppeteer.default.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  await browser.close();
  puppeteerAvailable = true;
} catch {
  console.warn('⚠️  Skipping PDF integration tests: Puppeteer not available or cannot launch browser');
}

const describeOrSkip = puppeteerAvailable ? describe : describe.skip;

describeOrSkip('PDF Export Integration (real Puppeteer — no mocks)', () => {
  afterAll(async () => {
    await disconnectTestDb();
  });

  describe('generatePdf — low-level Puppeteer PDF generation', () => {
    it('generates a valid PDF buffer from a simple HTTP page', async () => {
      // Test Puppeteer directly by rendering a simple page.
      // We use the frontend URL (which may or may not be running).
      // If it's not running, Puppeteer will still generate a PDF of an error page,
      // which is fine — we're testing that Puppeteer itself works.
      const puppeteer = await import('puppeteer');

      const browser = await puppeteer.default.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });

      try {
        const page = await browser.newPage();
        await page.setContent('<html><body><h1>Test Report</h1><p>Generated by IPIS PDF pipeline</p></body></html>');
        const pdfBuffer = await page.pdf({
          format: 'A4',
          landscape: true,
          printBackground: true,
          margin: { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
        });

        const buffer = Buffer.from(pdfBuffer);

        expect(buffer).toBeInstanceOf(Buffer);
        expect(buffer.length).toBeGreaterThan(500);
        expect(buffer.subarray(0, 5).toString()).toBe('%PDF-');
      } finally {
        await browser.close();
      }
    }, 30000);
  });

  describe('exportPdf — service-level integration', () => {
    let financeUser: { id: string; role: string; email: string };
    let projectId: string;

    beforeEach(async () => {
      await cleanDb();

      const depts = await seedTestDepartments();

      const finance = await createTestUser('FINANCE', {
        departmentId: depts.get('Finance'),
      });
      financeUser = { id: finance.id, role: finance.role, email: finance.email };

      const dm = await createTestUser('DELIVERY_MANAGER', {
        departmentId: depts.get('Delivery'),
      });

      const project = await prisma.project.create({
        data: {
          name: 'Integration Test Project',
          client: 'Test Client',
          vertical: 'IT Services',
          engagementModel: 'TIME_AND_MATERIALS',
          status: 'ACTIVE',
          deliveryManagerId: dm.id,
          startDate: new Date('2026-01-01'),
          endDate: new Date('2026-12-31'),
        },
      });
      projectId = project.id;
    });

    it('generates a valid PDF for company report (no entityId)', async () => {
      // Import without mocks — real Puppeteer
      const reportService = await import('./report.service.js');

      // Company reports don't need entityId (Story 13.7 fix)
      const result = await reportService.exportPdf('company', undefined, '2026-03', financeUser);

      expect(result.buffer).toBeInstanceOf(Buffer);
      expect(result.buffer.length).toBeGreaterThan(100);
      expect(result.buffer.subarray(0, 5).toString()).toBe('%PDF-');
      expect(result.filename).toBe('IPIS-company-2026-03.pdf');
    }, 30000);

    it('generates a valid PDF for project report with entityId', async () => {
      const reportService = await import('./report.service.js');

      const result = await reportService.exportPdf('project', projectId, '2026-03', financeUser);

      expect(result.buffer).toBeInstanceOf(Buffer);
      expect(result.buffer.length).toBeGreaterThan(100);
      expect(result.buffer.subarray(0, 5).toString()).toBe('%PDF-');
      expect(result.filename).toBe(`IPIS-project-${projectId}-2026-03.pdf`);
    }, 30000);

    it('produces correct filename for executive report', async () => {
      const reportService = await import('./report.service.js');

      const result = await reportService.exportPdf('executive', undefined, '2026-02', financeUser);

      expect(result.buffer.subarray(0, 5).toString()).toBe('%PDF-');
      expect(result.filename).toBe('IPIS-executive-2026-02.pdf');
    }, 30000);
  });
});
